import { defineStore } from 'pinia'
import createClient from "openapi-fetch";
import type { paths, components } from "../generated/api-schema"; // generated by openapi-typescript

export const useBookmarkStore = defineStore('bookmark', {
    state: () => ({
        client : createClient<paths>({ baseUrl: "http://localhost:5054/" }),
        bookmarks: [] as (components["schemas"]["Bookmark"])[]
    }),
    // getters: {
    //   bookmarks: (state) => state.bookmarks,
    // },
    actions: {
      async load() {
        const { data, error } = await this.client.GET("/api/WorldParser/bookmarks");
        if (error !== undefined) {
          console.error(error)
        } else {
          this.bookmarks = data;
          console.log(this.bookmarks)
        }
      },
    },
  })